### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_

### ISSUE THREAD

**Issue by FarzanT** [PaccMann/paccmann_predictor#14]
Hello, I get the following error when running on default data from the IBM folder.
```
Traceback (most recent call last):
  File "./examples/IC50/train_paccmann.py", line 347, in <module>
    args.training_name
  File "./examples/IC50/train_paccmann.py", line 278, in main
    torch.Tensor(predictions), torch.Tensor(labels)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```
The model was able to finish 1 epoch and print it's loss, but then the error appeared.

Thank you!

**Comment by jannisborn** [comment]
Hi @FarzanT 
You cant convert a np array of type _object_ to a torch Tensor. I'd cast it first to one of the mentioned types and then convert it.

**Comment by FarzanT** [comment]
Thank you, but I'm using the data you posted, not custom data. Just trying to recreate your results. Perhaps there's a version mismatch? This is the exact command I'm using (note that I changed `args` positional arguments to keyword arguments to reduce confusion):
```
python3 ./examples/IC50/train_paccmann.py --train_sensitivity_filepath ccle_ic50_train_fraction_0.9_id_246_seed_42.csv --test_sensitivity_filepath ccle_ic50_train_fraction_0.9_id_246_seed_42.csv --gep_filepath ccle-rma_gene-expression.csv --smi_filepath ccle.smi --gene_filepath 2128_genes.pkl --smiles_language_filepath smiles_language.pkl --model_path /scratch/ --params_filepath examples/IC50/example_params.json --training_name PaccMannTest
```
I'm using the your data, and wanna measure the model's training set performance, that's why the train and test paths are the same.

**Comment by jannisborn** [comment]
Yes, your code does not break because of the data. Maybe it's a version mismatch, I cant say from your example. Just fix the type conversion and move ahead, all that matters is converting to a type that can be understood by the `pearsonr` function.
