### ISSUE TITLE
Can't Generate the SMILES_Language_Object.

### ISSUE THREAD

**Issue by DBinary** [PaccMann/paccmann_predictor#24]
Sorry，I cant generate the "SMILES language object", which is used to train a new model.
Do you have the code to generate such objects?
Thank you so much.

**Comment by jannisborn** [comment]
This depends a bit on which code of this repo you are running. In the old/deprecated code version, the smiles language was a `.pkl` object. I would recommend to run the current version of the code which relies on a `pytoda` version >=1.0.0. In this case, everything that defines a smiles language will be stored in readable `.json`  files that are in a designated folder. I recommend you to use the smiles language that is natively inside `pytoda`. See here: https://github.com/PaccMann/paccmann_datasets/tree/master/pytoda/smiles/metadata/tokenizer

Unless your data has very obscure SMILES tokens, this should work out of the Box. But if needed, you can copy/adapt this folder according to your needs.
To train a model, you will need to provide the path to this folder linked above. Here's how:


After you `pip install pytoda`, you can run
```py
import os
import pytoda.smiles.metadata as meta
print(os.path.join(os.path.dirname(meta.__file__), 'tokenizer'))
```
which should show you the path to the tokenizer in the local directory. Hope this helps!

**Comment by jannisborn** [comment]
Feel free to reopen if needed
