### ISSUE TITLE
A interesting bug for paccmann_predictor training.

### ISSUE THREAD

**Issue by DBinary** [PaccMann/paccmann_predictor#26]
I'm sorry to bother you again.
This was a bug I haven't encountered before，when we used your code to training a paccmann_predictor model, here was a bug that hasn't appeared in past training. The type of min_loss was 'str', so that there was a error that "TypeError: '<' not supported between instances of 'float' and 'str'".I dont know why, maybe I need your help.
You can find the error picture here: ![error](https://imgur.com/a/fvmCbmm)

**Comment by DBinary** [comment]
Maybe the picture cannot be displayed properly.
The website is here: https://imgur.com/a/fvmCbmm

**Comment by jannisborn** [comment]
The casting you do looks great, please feel free to submit a PR.
