### ISSUE TITLE
Error when testing on the example dataset

### ISSUE THREAD

**Issue by Qianhui-Zheng** [PaccMann/paccmann_predictor#27]
Hi I was trying to train the model using the example data provided, but I get the following error:

Traceback (most recent call last):
  File "./paccmann_predictor/examples/IC50/train_paccmann.py", line 343, in <module>
    main(
  File "./paccmann_predictor/examples/IC50/train_paccmann.py", line 279, in main
    predictions = np.array([p.cpu() for preds in predictions for p in preds])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6144,) + inhomogeneous part.

Thanks!

**Comment by jannisborn** [comment]
Hi, 
Thanks for the interest in this work.
In that case, you will have to adapt the code to read out all items from `predictions` individually before stacking them to a new `np.array`
