### ISSUE TITLE
How to prepare the gene expression data?

### ISSUE THREAD

**Issue by Pascal-Iv** [PaccMann/paccmann_predictor#6]
The GDSC database has grown and I am trying to retrain the PaccMann predictor with more data.
In your paper, you state that: "RMA-normalized gene expression data were retrieved from the GDSC database". I am sure this relates to the file _RMA normalized basal expression profiles for all the cell-lines_ [on this GDSC page](https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources/Home.html). However this does not match the data you provide at the [Box@IBM](https://ibm.ent.box.com/s/vfehvfly7mi2obvaj86pjuy9a82e8nik/folder/79293026490).
As an example, I plotted the distribution of the gene expression for the 2128 network propagation genes for the cell line SAT. I z-normalized the data I attained from GDSC.

![GEdistributions](https://user-images.githubusercontent.com/55785079/92301964-664a3d00-ef68-11ea-9f27-70045ccee351.png)

What kind of data source/ normalization did you use to prepare the GE data?

Thanks!

**Comment by jannisborn** [comment]
Hi @Pascal-Iv,
Thanks for your interest. You are right that our manuscript is not too specific about this bit and we apologize for that. For each gene, we first did an `arcsinh` transformation which is similar to a `log` but has [some beneficial properties](https://www.ascistance.co.uk/blog/transcriptomics/renormalise-data-with-arcsinh-instead-of-log/). Then, we performed a z-standardization which led us to the data that we published on Box. Please also note that on Box, we make all the standardization paramaters (mean and stds) available.

Hope this helps!

**Comment by Pascal-Iv** [comment]
Thanks, @jannisborn for the quick response!
